//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';

//forms
export const FORMS_FETCH_START = 'FORMS_FETCH_START';
export const FORMS_FETCH_SUCCESS = 'FORMS_FETCH_SUCCESS';
export const FORMS_FETCH_FAIL = 'FORMS_FETCH_FAIL';
export const FORMS_ADD_SCHEMA = 'FORMS_ADD_SCHEMA';

//profiles
export const PROFILES_FETCH_START = 'PROFILES_FETCH_START';
export const PROFILES_FETCH_SUCCESS = 'PROFILES_FETCH_SUCCESS';
export const PROFILES_FETCH_FAIL = 'PROFILES_FETCH_FAIL';
export const PROFILES_FETCH_CANCEL = 'PROFILES_FETCH_CANCEL';
//profile
export const PROFILE_FETCH_SCHEMA_START = 'PROFILE_FETCH_SCHEMA_START';
export const PROFILE_FETCH_SCHEMA_SUCCESS = 'PROFILE_FETCH_SCHEMA_SUCCESS';
export const PROFILE_FETCH_SCHEMA_FAIL = 'PROFILE_FETCH_SCHEMA_FAIL';
export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL';
export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_DELETE = 'PROFILE_DELETE';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_RESET_ID = 'PROFILE_RESET_ID';
export const PROFILE_FORMATTED_FORM_CREATED = 'PROFILE_FORMATTED_FORM_CREATED';
export const PROFILE_FORMAT_SCHEMA_WITH_DATA = 'PROFILE_FORMAT_SCHEMA_WITH_DATA';

//ui
export const UI_SHOW_TOOLBAR = 'UI_SHOW_TOOLBAR';

//components
export const COMPONENTS_FETCH_START = 'COMPONENTS_FETCH_START';
export const COMPONENTS_FETCH_SUCCESS = 'COMPONENTS_FETCH_SUCCESS';
export const COMPONENTS_FETCH_FAIL = 'COMPONENTS_FETCH_FAIL';
